### PR TITLE
Fix getPlayerTilePosition() and add corresponding test case

### LINKED ISSUE #28: Missing command in `getPlayerTilePosition()`
### Description:
The `getPlayerTilePosition()` function in the `MinecraftConnection` class contains a potential issue where the command `player.` is incomplete. This could lead to unexpected behavior or errors when attempting to retrieve the player's position.

**Code Snippet:**
```cpp
Coordinate MinecraftConnection::getPlayerTilePosition() {
    std::string returnString = conn->sendReceiveCommand("player.", "");
    std::vector<int> parsedInts;
    splitCommaStringToInts(returnString, parsedInts);
    return Coordinate(parsedInts[0], parsedInts[1], parsedInts[2]);
}

### PR DESCRIPTION
**Pull request by nhatdongdang**
### Description
This pull request fixes the incomplete command in the `getPlayerTilePosition()` function.

**Changes:**
- Updated the command from `player.` to `player.getTile`.
- Added corresponding test case for getPlayerTilePosition() and setPlayerTilePosition()

### Linked Issue
This pull request fixes #28

### CODE REVIEW

File: test/minecraft_tests.cpp [hunk 1]
```diff
@@ -153,6 +153,19 @@ TEST_CASE("Test the main mcpp class") {
...
+        Coordinate testLoc2(testLoc1.x, testLoc1.y - 1, testLoc1.z);
+
+        mc.setBlock(testLoc2, Blocks::DIRT);
+        mc.setPlayerTilePosition(testLoc1);
+
+        Coordinate result = mc.getPlayerTilePosition();
+        Coordinate expected(180, 100, 154);
+
+        CHECK_EQ(result, expected);
+    }
```
Comment (rozukke) [inline test/minecraft_tests.cpp]: This should be under the `PLAYER_TEST` section, as it requires a running instance of Minecraft.

**Review by rozukke — CHANGES_REQUESTED** [review]
I know why maintainers become grumpy so quickly now... Thanks for the catch.

**Review by rozukke — APPROVED** [review]
LGTM for now 👍
Update pending in an upcoming PR
