### PR TITLE
Fix get/set(PlayerTilePosition) offset by 1

### LINKED ISSUE #30: `getPlayerPosition` and `getPlayerTilePosition` are equivalent
## Description ##
The `Coordinate` class currently only supports integer fields. This limitation causes the `getPlayerPosition` method to behave the same as `getPlayerTilePosition`, and `setPlayerPosition` to behave the same as `setPlayerTilePosition`.

### PR DESCRIPTION
**Pull request by johnathanchann**
## Related Issue
Fixes #30  

## Type of Change
- Offset getTilePosition by -1
- Offset setTilePosition by +1

**Tested with test_suite**
```
----------------------------------------------------------

2/2 Testing: full
2/2 Test: full
Command: "/mnt/c/Users/yeefh/documents/mcpp/build/test/test_suite"
Directory: /mnt/c/Users/yeefh/documents/mcpp/build
"full" start time: Jun 12 00:07 AEST
Output:
----------------------------------------------------------
[doctest] doctest version is "2.4.9"
[doctest] run with "--help" for options
===============================================================================
[doctest] test cases:  6 |  6 passed | 0 failed | 0 skipped
[doctest] assertions: 40 | 40 passed | 0 failed |
[doctest] Status: SUCCESS!
<end of output>
Test time =   0.92 sec
----------------------------------------------------------
Test Passed.
"full" end time: Jun 12 00:07 AEST
"full" time elapsed: 00:00:00
----------------------------------------------------------

End testing: Jun 12 00:07 AEST
```

### CODE REVIEW

File: src/mcpp.cpp [hunk 1]
```diff
@@ -45,14 +45,15 @@ Coordinate MinecraftConnection::getPlayerPosition() {
 }
 
 void MinecraftConnection::setPlayerTilePosition(const Coordinate& tile) {
-    conn->sendCommand("player.setTile", tile.x, tile.y, tile.z);
+    Coordinate newTile = tile;
+    newTile.y++;
+    conn->sendCommand("player.setTile", newTile.x, newTile.y, newTile.z);
```
Comment (rozukke) [inline src/mcpp.cpp]: Why is `getPlayerTilePosition` done in terms of `getPlayerPosition` but this is done manually? Ideally this would be `setPlayerPosition(tile + Coord{ 0, 1, 0})` or something similar.

**Review by rozukke — COMMENTED** [review]
Just some consistency updates and should be good to go - make sure that player tests correspond to this functionality too.

File: src/mcpp.cpp (hunk 1 above)
Comment (johnathanchann) [reply src/mcpp.cpp]: Thanks for catching it, will resolve this right now.
